version: "3"
services:
  
  website:
    image: demok8s:latest
    build:
      context: ../
      dockerfile: docker/dockerfile
      args:
        env: ${DOCKER_ENV}
    container_name: demok8s
    # environment:
      # ASPNETCORE_ENVIRONMENT: Docker
      # ASPNETCORE_Kestrel__Certificates__Default__Password:
      # ASPNETCORE_Kestrel__Certificates__Default__Path: "/etc/docker/certs/docker.pfx"
    networks: 
      - default
    ports:
      - ${EXPOSED_HTTP_PORT}:5000
      - ${EXPOSED_HTTPS_PORT}:5001

networks:
  default:
    driver: bridge