---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-blue-service # The name of the service
spec:
  type: NodePort
  selector:
    app: demo-k8s-blue # The lable of pods
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      # nodePort: 30601

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-grey-service # The name of the service
spec:
  type: NodePort
  selector:
    app: demo-k8s-grey # The lable of pods
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      # nodePort: 30602