---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-blue-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-k8s-blue
    spec:
      containers:
        - name: demok8s
          image: karatejb/demo-k8s:blue-theme
          ports:
            - containerPort: 5001
  selector:
    matchLabels:
      app: demo-k8s-blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-grey-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-k8s-grey
    spec:
      containers:
        - name: demok8s
          image: karatejb/demo-k8s:grey-theme
          ports:
            - containerPort: 5001
  selector:
    matchLabels:
      app: demo-k8s-grey