---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-k8s-ingress
  namespace: demo-k8s
  # annotations:
    # use the shared ingress-nginx
    # kubernetes.io/ingress.class: "nginx"
  # annotations:
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: demo-k8s-blue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-k8s-blue-service
                port:
                  number: 80
    - host: demo-k8s-grey.com
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: demo-k8s-grey-service
                port:
                  number: 80