---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-k8s-ingress
spec:
  rules:
    - host: demo-k8s-blue.com
      http:
        paths:
          - backend:
              service:
                name: demo-k8s-blue-service
                port: 
                  number: 5001
    - host: demo-k8s-grey.com
      http:
        paths:
          - backend:
              service:
                name: demo-k8s-grey-service
                port: 
                  number: 5001