" Set default shell
set shell=\"C:/Program\ Files/Git/usr/bin/bash.exe\"

" Custom settings
set number
set relativenumber
set history=200
set guifont=Consolas:h14
colors slate
highlight LineNr guifg=DarkGray
highlight Search guibg='Purple' guifg=#FFFFFF
highlight String guifg=#FF5733
highlight Visual guibg=#000000
highlight Pmenu guifg=#000000 guibg=#808080
