---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-k8s-configmap
  labels:
    app: demo-k8s
data:
  appsettings.Kubernetes.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Customize": {
        "Theme": "#808080"
      }
    }
