---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-k8s-env-configmap
  labels:
    app: demo-k8s
data:
  ASPNETCORE_ENVIRONMENT: "Kubernetes"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-k8s-configmap
  labels:
    app: demo-k8s
data:
  appsettings.kubernetes.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "Customize": {
        "Theme": "#9d95df"
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demok8s
          image: karatejb/demo-k8s:latest # The Docker image
          ports:
            - containerPort: 5000
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: demo-k8s-env-configmap
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.Kubernetes.json
              subPath: appsettings.Kubernetes.json
      volumes:
        - name: config-volume
          configMap:
            name: demo-k8s-configmap
  selector: # The label selector
    matchLabels:
      app: demo-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: demo-k8s
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: https-port
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
