# Before apply this manifest, create the ConfigMap as following.
# kubectl create cm demo-k8s-configmap --from-file=./appsettings.kubernetes.json --from-literal=aspnetcore-environment="kubernetes" --from-literal=aspnetcore-forwardedheaders-enabled="true" -n demo-k8s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demok8s
          image: karatejbacr.azurecr.io/demo-k8s:latest # The Docker image
          ports:
            - containerPort: 5000
            - containerPort: 5001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: demo-k8s-configmap
                  key: ap-env
          volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.kubernetes.json
              subPath: appsettings.kubernetes.json
      imagePullSecrets:
        - name: acrcred
      volumes:
        - name: config-volume
          configMap:
            name: demo-k8s-configmap
  selector: # The label selector
    matchLabels:
      app: demo-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: demo-k8s
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: https-port
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
