---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-k8s-env-secret
  labels:
    app: demo-k8s
data:
  ASPNETCORE_ENVIRONMENT: S3ViZXJuZXRlcw==
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: dHJ1ZQ==

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-k8s-secret
  labels:
    app: demo-k8s
data:
  appsettings.Kubernetes.json: ew0KICAiTG9nZ2luZyI6IHsNCiAgICAiTG9nTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAiTWljcm9zb2Z0IjogIldhcm5pbmciLA0KICAgICAgIk1pY3Jvc29mdC5Ib3N0aW5nLkxpZmV0aW1lIjogIkluZm9ybWF0aW9uIg0KICAgIH0NCiAgfSwNCiAgIkN1c3RvbWl6ZSI6IHsNCiAgICAiVGhlbWUiOiAiIzlkOTVkZiINCiAgfQ0KfQ0K

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demok8s
          image: karatejb/demo-k8s:latest # The Docker image
          ports:
            - containerPort: 5000
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: demo-k8s-env-secret
          volumeMounts:
            - name: secret-volume
              mountPath: /app/appsettings.Kubernetes.json
              subPath: appsettings.Kubernetes.json
      # imagePullSecrets:
      #   - name: acrcred
      volumes:
        - name: secret-volume
          secret:
            secretName: demo-k8s-secret
  selector: # The label selector
    matchLabels:
      app: demo-k8s

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-service
spec:
  selector:
    app: demo-k8s
  ports:
    - name: http-port
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: https-port
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
