---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-k8s-secret
  labels:
    app: demo-k8s
data:
  appsettings.Kubernetes.json: ew0KICAiTG9nZ2luZyI6IHsNCiAgICAiTG9nTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAiTWljcm9zb2Z0IjogIldhcm5pbmciLA0KICAgICAgIk1pY3Jvc29mdC5Ib3N0aW5nLkxpZmV0aW1lIjogIkluZm9ybWF0aW9uIg0KICAgIH0NCiAgfSwNCiAgIkN1c3RvbWl6ZSI6IHsNCiAgICAiVGhlbWUiOiAiIzlkOTVkZiINCiAgfQ0KfQ0K