---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-k8s-env-secret
  labels:
    app: demo-k8s
data:
  ASPNETCORE_ENVIRONMENT: S3ViZXJuZXRlcw==
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: dHJ1ZQ==