### 
### Start dotnet build layer
###
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# Copy source code and restore as distinct layers
COPY src/ ./src

# Copy some other artifects, such as certificate.
COPY docker/ ./docker

# Build the application 
WORKDIR "/app/src/MyApp"
RUN dotnet restore
RUN dotnet publish --configuration release --output "/app/publish"



### 
### Start dotnet runtime layer
###

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

WORKDIR /app
COPY --from=build "/app/publish" ./
RUN mkdir -p /etc/docker/certs/ 
COPY docker/certs/myapp.pfx /etc/docker/certs/
# rename the certificate
RUN mv /etc/docker/certs/myapp.pfx /etc/docker/certs/docker.pfx
VOLUME /app/App_Data/Logs

ENV TZ "Asia/Taipei"
# ENV LANG "zh_TW.UTF-8"
# ENV LANGUAGE "zh_TW.UTF-8"
# ENV LC_ALL "zh_TW.UTF-8"
ENV ASPNETCORE_URLS "http://+:5000;https://+:5001"
ENV ASPNETCORE_ENVIRONMENT production 
ENV ASPNETCORE_Kestrel__Certificates__Default__Password ""
ENV ASPNETCORE_Kestrel__Certificates__Default__Path "/etc/docker/certs/docker.pfx"
EXPOSE 5000 5001

ENTRYPOINT ["dotnet", "MyApp.dll"]

