#### Build stage: based on Node.js ####
FROM node:12 as build
WORKDIR /app

# Copy source code
COPY demok8s/ ./
RUN npm install
ARG configuration=production
RUN npm run build -- --output-path=./dist --configuration $configuration

#### Runtime stage ####
FROM nginx:1.17.5 AS runtime
# Arg for current environment, eg. Development, Docker, Production. Use docker-compose file to overwrite.
ARG env="Docker"

# Copy build artifects
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY ./docker/certs/${env}.crt /etc/nginx/certs/
COPY ./docker/certs/${env}.key /etc/nginx/certs/
RUN mv /etc/nginx/certs/${env}.crt /etc/nginx/certs/docker.crt
RUN mv /etc/nginx/certs/${env}.key /etc/nginx/certs/docker.key

# Copy default nginx configuration
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf