version: "3"
services:
  
  website:
    image: demo-k8s-web:latest
    build:
      context: ../
      dockerfile: docker/dockerfile
      args:
        env: ${DOCKER_ENV}
    container_name: demo-k8s-web
    # environment:
    networks: 
      - default
    ports:
      - ${EXPOSED_HTTP_PORT}:80
      - ${EXPOSED_HTTPS_PORT}:443

networks:
  default:
    driver: bridge